dist: trusty
group: travis_latest
language: ruby
rvm: 2.5.1
branches:
  except:
  - "/^v\\d/"
before_install: gem update bundler
install: bundle install --without development system_tests --path vendor/bundle
script: bundle exec rake test
env:
  global:
  - CI_NODE_TOTAL=2
  matrix:
  - CI_NODE_INDEX=1
  - CI_NODE_INDEX=2
cache:
  directories:
  - vendor/bundle
  - modules
notifications:
  webhooks:
    urls: https://vbot.ghn.me/travis
  slack:
    secure: gtSaaanBmNqDSMBW7birtnL9bB9m8r5DifhAPY906H/IBSY/NyDEDlWkzh8R8v4SLMhy4O1GgF8HiNsgGT1BUI7KTwlOl1OEYx9D9MELs3c+YBiUhYLI6Qwb1ylX0Ytyemp6pyvhoLzBKcrtVMIIuIGsF1Zffl9zYookPVWpxYAXOj+ZuQBJk6Rr4mhSgs/NjNflBhkznzB6od1ycHqbTBhhqZPAWXAYZhuKrIjnORbCy5wUQWoBwR0D1l5N3uiSM1kl3qLycqHuW9PhHKxYGIQI+lR8FcAU/61WzbDs46QbQsHcdltZWb7XLmEHZkBbicpy8E5rYKi44FWRigatmL3mVU59qX+iR25z9FMZ3558vWboLTQGoCLLyj4wIcUzCxJij38rQrjpzzSSYCCNK3U4RuRkSHa2L9DS1DDnPUMzE8LCksWGQAdcWXbpiPZG99yb2HxEMiHJnNugbyDOqcDBUQO8GYjJuuQQwzlfQKImoCVAxiem0lfpwUKScporwiO61F1tQZRVSRkgaOvQeReZ4kWbLmAQlC/eM2m+TtyZZYw/jI8QXyjQtdDWSLLf9bGlTOHaFSBhrQr5G5U1xN9jrHsjDzXmEyTuPj51nZiryU0cA/bmYy53k2v3B/51BYe3ZLUv7ya+wMWpONy4vH+E+NVRJk0ImGquNNb7bY0=
