#!/usr/bin/env bash

# Bash strict mode
set -euo pipefail
IFS=$'\n\t'

# Paths
export APPDIR TMPDIR
APPDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
TMPDIR=$(mktemp -d 2>/dev/null || mktemp -d -t 'tmp')

# Internal paths
export PRIVATE_DATA_DIR="${APPDIR}/.private"
export HIERA_DATA_DIR="${APPDIR}/hieradata"

# Load private environment
# shellcheck disable=1090
. "${APPDIR}/.private/.env" 2>/dev/null || true

# Load VGS library
# shellcheck disable=1090,1091
. /opt/vgs/load 2>/dev/null || . ~/vgs/load 2>/dev/null || true

# Load functions
for file in ${APPDIR}/lib/*.sh; do
  # shellcheck disable=1090
  . "$file"
done

# Detect environment
GIT_BRANCH=$(git -C "$APPDIR" symbolic-ref --short HEAD 2>/dev/null || echo '')
GIT_SHA1=$(git -C "$APPDIR" rev-parse --short HEAD 2>/dev/null || echo '0')

## Detect if git directory or if Travis CI or if AWS CodeDeploy
if [[ -n "${ENVTYPE:-}" ]]; then
  ENVTYPE="$ENVTYPE"
elif [[ -n "${GIT_BRANCH:-}" ]]; then
  ENVTYPE="$GIT_BRANCH"
elif [[ -n "${TRAVIS_BRANCH:-}" ]]; then
  ENVTYPE="$TRAVIS_BRANCH"
elif [[ -n "${CIRCLE_BRANCH:-}" ]]; then
  ENVTYPE="$CIRCLE_BRANCH"
elif [[ -n "${DEPLOYMENT_GROUP_NAME:-}" ]]; then
  ENVTYPE="$DEPLOYMENT_GROUP_NAME"
else
  ENVTYPE=${ENVTYPE:-production}
fi
export ENVTYPE

# CI
export CI=${CI:-false}
export PR=false
export BUILD=${GIT_SHA1:-0}
if [[ ${CIRCLECI:-false} == true ]]; then
  export PR=${CIRCLE_PR_NUMBER}
  export BUILD=${CIRCLE_BUILD_NUM}
  git config --global user.name "CircleCI"
elif [[ ${TRAVIS:-false} == true ]]; then
  export PR=${TRAVIS_PULL_REQUEST}
  export BUILD=${TRAVIS_BUILD_NUMBER}
  git config --global user.name "TravisCI"
fi

# AWS
export AWS_ASSETS_BUCKET='vladgh'
export AWS_DEFAULT_REGION="${AWS_DEFAULT_REGION:-us-east-1}"
export ARCHIVE_S3PATH="s3://${AWS_ASSETS_BUCKET}/${ENVTYPE}.tgz"
export PP_HIERADATA_S3="s3://${AWS_ASSETS_BUCKET}/hieradata/${ENVTYPE}"
export PP_PRIVATE_DATA_S3="s3://${AWS_ASSETS_BUCKET}/private/${ENVTYPE}"
