#!/usr/bin/env bash

# Bash strict mode
set -euo pipefail
IFS=$'\n\t'

# VARs
export APPDIR TMPDIR
APPDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
TMPDIR=$(mktemp -d 2>/dev/null || mktemp -d -t 'tmp')

# Internal paths
export PRIVATE_DATA_REPO="${APPDIR}/.private"
export HIERA_DATA_REPO="${APPDIR}/hieradata"
export PRIVATE_DATA="/etc/puppetlabs/private"
export HIERA_DATA="/etc/puppetlabs/hieradata"

# Other
export NOW
NOW="$(date +"%Y%m%d_%H%M")"

# Load private environment
# shellcheck disable=1090
. "${APPDIR}/.env" 2>/dev/null || true

# Load VGS library
# shellcheck disable=1090,1091
. /opt/vgs/load 2>/dev/null || . ~/vgs/load 2>/dev/null || true

# Load functions
for file in ${APPDIR}/lib/*.sh; do
  # shellcheck disable=1090
  . "$file"
done

# Version
export VERSION_FILE="${APPDIR}/VERSION"
export CHANGELOG_FILE="${APPDIR}/CHANGELOG.md"
export VERSION; VERSION=$(cat "$VERSION_FILE" || echo '0.0.0')

# Detect environment
GIT_BRANCH=$(git -C "$APPDIR" symbolic-ref --short HEAD 2>/dev/null || echo '')
GIT_SHA1=$(git -C "$APPDIR" rev-parse --short HEAD 2>/dev/null || echo '0')
if [[ -n "${ENVTYPE:-}" ]]; then
  ENVTYPE="$ENVTYPE"
elif [[ -n "${GIT_BRANCH:-}" ]]; then
  ENVTYPE="$GIT_BRANCH"
elif [[ -n "${TRAVIS_BRANCH:-}" ]]; then
  ENVTYPE="$TRAVIS_BRANCH"
elif [[ -n "${CIRCLE_BRANCH:-}" ]]; then
  ENVTYPE="$CIRCLE_BRANCH"
elif [[ -n "${DEPLOYMENT_GROUP_NAME:-}" ]]; then
  ENVTYPE="$DEPLOYMENT_GROUP_NAME"
else
  ENVTYPE=${ENVTYPE:-production}
fi
if [[ "$ENVTYPE" == 'master' ]]; then
  export ENVTYPE='production'
else
  export ENVTYPE
fi

# CI
export CI=${CI:-false}
export PR=false
export BUILD=${GIT_SHA1:-0}
if [[ ${CIRCLECI:-false} == true ]]; then
  export PR=${CIRCLE_PR_NUMBER}
  export BUILD=${CIRCLE_BUILD_NUM}
  git config --global user.name "CircleCI"
elif [[ ${TRAVIS:-false} == true ]]; then
  export PR=${TRAVIS_PULL_REQUEST}
  export BUILD=${TRAVIS_BUILD_NUMBER}
  git config --global user.name "TravisCI"
fi

# AWS
export AWS_ASSETS_BUCKET='vladgh'
export AWS_DEFAULT_REGION="${AWS_DEFAULT_REGION:-us-east-1}"
export S3_SSL="s3://${AWS_ASSETS_BUCKET}/ssl"
export S3_SSL_BACKUP="s3://${AWS_ASSETS_BUCKET}/backup/ssl_${NOW}.tgz"
export S3_ARTIFACTS="s3://${AWS_ASSETS_BUCKET}/artifacts"
export S3_HIERADATA="s3://${AWS_ASSETS_BUCKET}/hieradata/${ENVTYPE}"
export S3_PRIVATE_DATA="s3://${AWS_ASSETS_BUCKET}/private/${ENVTYPE}"
export S3_HIERADATA_ALL="s3://${AWS_ASSETS_BUCKET}/hieradata"
export S3_PRIVATE_DATA_ALL="s3://${AWS_ASSETS_BUCKET}/private"
