#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

# Redirect stdout/stderr to a file
exec &> /tmp/r10k_post_run.log

# VARs
BUCKET=vladgh
PREFIX=hieradata
ENV_PATH=/etc/puppetlabs/code/environments

# AWS
AZ=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone || echo 'us-east-1a')
REGION="${AZ%?}"

# Download Private Hieradata
for envdir in ${ENV_PATH}/*; do
  [[ -d $envdir ]] || break
  envname=$(basename "$envdir")
  echo "Synchronize s3://${BUCKET}/${PREFIX}/${envname} -> ${envdir}/hieradata/"
  aws --region "$REGION" s3 sync --delete \
    "s3://${BUCKET}/${PREFIX}/${envname}/" \
    "${envdir}/hieradata/" || break
done
