#!/usr/bin/env bash
# GIT Pre-Push Hook
# @author Vlad Ghinea

# Load environment
# shellcheck disable=1090
. "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)/../../environment.sh" || true

main(){
  e_info 'Sync hiera data'
  aws s3 sync "${APPDIR}/data" "${AWS_ASSETS_S3_PATH}/data" --delete
  e_info 'Sync dotenv'
  aws s3 cp "${APPDIR}/.env" "${AWS_ASSETS_S3_PATH}/.env"
}

# Info
e_header 'INFO:'
e_info "Application directory: ${APPDIR:?}"
e_info "AWS S3 Path: ${AWS_ASSETS_S3_PATH:?}"

# Process arguments
e_header 'AWS Image:'
main "$@"
