#!/usr/bin/env bash
# This hook syncs the templates in the master branch to an AWS S3 bucket.
# @author Vlad Ghinea

# Fail on errors
set -e

# Load environment
export AWS_PROFILE=cosmin
PATH=/usr/local/bin:${PATH}
CURDIR=$(git rev-parse --show-toplevel)
BRANCH="$(git symbolic-ref --short HEAD)"
if [[ "$BRANCH" == 'master' ]]; then
  ENV='production'
else
  ENV="$BRANCH"
fi
DATA_DIR="${CURDIR}/data"
S3_PATH="s3://ansassetswest/data/${ENV}"

# Upload Private Data to S3
if aws s3 sync "${DATA_DIR}/" "${S3_PATH}/" \
  --delete --acl private; then
    echo "Synced ${DATA_DIR} to ${S3_PATH}"
else
  echo "Could not sync ${DATA_DIR} to ${S3_PATH}"; exit 1
fi
